/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import controleurs.Controleur;
import javax.swing.DefaultComboBoxModel;
import controleurs.CtrlAccueil;
import java.util.logging.Level;
import java.util.logging.Logger;
import modele.dao.DaoException;

public class VueAccueil extends VueAbstraite {

    DefaultComboBoxModel modeleJComboBoxAccueil;


    public VueAccueil(Controleur ctrl) {
        super(ctrl);
        initComponents();
        modeleJComboBoxAccueil= new DefaultComboBoxModel();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonComptesRendus = new javax.swing.JButton();
        jButtonVisiteurs = new javax.swing.JButton();
        jLabelTitre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonComptesRendus.setText("Comptes rendus");
        jButtonComptesRendus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComptesRendusActionPerformed(evt);
            }
        });

        jButtonVisiteurs.setText("Visiteurs");
        jButtonVisiteurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisiteursActionPerformed(evt);
            }
        });

        jLabelTitre.setText("Gestion des comptes rendus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButtonVisiteurs))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButtonComptesRendus))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitre)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButtonComptesRendus)
                .addGap(46, 46, 46)
                .addComponent(jButtonVisiteurs)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisiteursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisiteursActionPerformed
        try {
            ((CtrlAccueil)controleur).afficherVisiteur();
        } catch (DaoException ex) {
            Logger.getLogger(VueAccueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonVisiteursActionPerformed

    private void jButtonComptesRendusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComptesRendusActionPerformed
        try {
            ((CtrlAccueil)controleur).afficherRapport();
        } catch (DaoException ex) {
            Logger.getLogger(VueAccueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonComptesRendusActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComptesRendus;
    private javax.swing.JButton jButtonVisiteurs;
    private javax.swing.JLabel jLabelTitre;
    // End of variables declaration//GEN-END:variables

}