/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import com.toedter.calendar.JDateChooser;
import controleurs.Controleur;
import controleurs.CtrlCréerRapport;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modele.dao.DaoException;

/**
 *
 * @author btssio
 */
public class VueCréerRapport extends VueAbstraite {

    /**
     * Creates new form VueCréerRapport
     */
    public VueCréerRapport(Controleur ctrl) {
        super(ctrl);
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPatricien = new javax.swing.JTextField();
        jLabelBilan = new javax.swing.JLabel();
        jTextFieldMotifRapport = new javax.swing.JTextField();
        jLabelDateRapport = new javax.swing.JLabel();
        jLabelPraticien = new javax.swing.JLabel();
        jLabelMotifRapport = new javax.swing.JLabel();
        jTextAreaBilan = new javax.swing.JTextArea();
        jButtonValider = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jDateChooserDateRapport = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBilan.setText("Bilan :");

        jLabelDateRapport.setText("Date du rapport :");

        jLabelPraticien.setText("Praticien :");

        jLabelMotifRapport.setText("Motif du rapport :");

        jTextAreaBilan.setColumns(20);
        jTextAreaBilan.setRows(5);

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelBilan)
                        .addComponent(jLabelPraticien)
                        .addComponent(jLabelDateRapport)
                        .addComponent(jLabelMotifRapport))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButtonValider)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAnnuler)
                            .addComponent(jTextFieldMotifRapport, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jTextFieldPatricien)
                            .addComponent(jDateChooserDateRapport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jTextAreaBilan, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPraticien)
                    .addComponent(jTextFieldPatricien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDateRapport)
                    .addComponent(jDateChooserDateRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMotifRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMotifRapport))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAreaBilan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBilan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValider)
                    .addComponent(jButtonAnnuler))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        try {
            ((CtrlCréerRapport)controleur).enregistrerRapport();
        } catch (DaoException ex) {
            Logger.getLogger(VueCréerRapport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        ((CtrlCréerRapport)controleur).rapportAnnuler();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    public JButton getjButtonAnnuler() {
        return jButtonAnnuler;
    }

    public void setjButtonAnnuler(JButton jButtonAnnuler) {
        this.jButtonAnnuler = jButtonAnnuler;
    }

    public JButton getjButtonValider() {
        return jButtonValider;
    }

    public void setjButtonValider(JButton jButtonValider) {
        this.jButtonValider = jButtonValider;
    }

    public JDateChooser getjDateChooserDateRapport() {
        return jDateChooserDateRapport;
    }

    public void setjDateChooserDateRapport(JDateChooser jDateChooserDateRapport) {
        this.jDateChooserDateRapport = jDateChooserDateRapport;
    }

    public JLabel getjLabelBilan() {
        return jLabelBilan;
    }

    public void setjLabelBilan(JLabel jLabelBilan) {
        this.jLabelBilan = jLabelBilan;
    }

    public JLabel getjLabelDateRapport() {
        return jLabelDateRapport;
    }

    public void setjLabelDateRapport(JLabel jLabelDateRapport) {
        this.jLabelDateRapport = jLabelDateRapport;
    }

    public JLabel getjLabelMotifRapport() {
        return jLabelMotifRapport;
    }

    public void setjLabelMotifRapport(JLabel jLabelMotifRapport) {
        this.jLabelMotifRapport = jLabelMotifRapport;
    }

    public JLabel getjLabelPraticien() {
        return jLabelPraticien;
    }

    public void setjLabelPraticien(JLabel jLabelPraticien) {
        this.jLabelPraticien = jLabelPraticien;
    }

    public JTextArea getjTextAreaBilan() {
        return jTextAreaBilan;
    }

    public void setjTextAreaBilan(JTextArea jTextAreaBilan) {
        this.jTextAreaBilan = jTextAreaBilan;
    }

    public JTextField getjTextFieldMotifRapport() {
        return jTextFieldMotifRapport;
    }

    public void setjTextFieldMotifRapport(JTextField jTextFieldMotifRapport) {
        this.jTextFieldMotifRapport = jTextFieldMotifRapport;
    }

    public JTextField getjTextFieldPatricien() {
        return jTextFieldPatricien;
    }

    public void setjTextFieldPatricien(JTextField jTextFieldPatricien) {
        this.jTextFieldPatricien = jTextFieldPatricien;
    }

    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonValider;
    private com.toedter.calendar.JDateChooser jDateChooserDateRapport;
    private javax.swing.JLabel jLabelBilan;
    private javax.swing.JLabel jLabelDateRapport;
    private javax.swing.JLabel jLabelMotifRapport;
    private javax.swing.JLabel jLabelPraticien;
    private javax.swing.JTextArea jTextAreaBilan;
    private javax.swing.JTextField jTextFieldMotifRapport;
    private javax.swing.JTextField jTextFieldPatricien;
    // End of variables declaration//GEN-END:variables
}
